language: erlang
otp_release:
  - 18.3
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.3.0.zip
  - unzip -d elixir v1.3.0.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script: mix test
after_script:
  - MIX_ENV=docs mix deps.get
